version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatapp-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: 
      - .env
    volumes:
      - .:/app
    networks:
      - chat-network

  db:
    image: postgres:15
    container_name: chatapp-db
    restart: always
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-network

networks:
  chat-network:

volumes:
  postgres-data:
